version: '3'
services:
  apache:
    image: yagoalexandre00/ubuntu-php-apache:8.2
    ports:
      - 80:80
    restart: always
    volumes: 
      - ./moodle:/var/www/html
  database:
    image: mariadb:10.11
    ports:
      - 3306:3306
    volumes: 
      - ./mariadb_data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: ${MOODLE_PASSWORD}
  phpmyadmin:
    image: phpmyadmin:5.2.1
    ports:
      - 8080:80
    environment:
      PMA_HOSTS: database
